### ISSUE TITLE
On game startup: `AttributeError: 'Game' object has no attribute 'controller'`

### ISSUE THREAD

**Issue by MacDeth** [MacDeth/wvu-runner-game-team#1]
I get this error right after the first information screen that shows after the main menu consistently.

```
$ python3.6 main.py 
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 530, in <module>
    main()
  File "main.py", line 521, in main
    g.lvl_select_init()
  File "main.py", line 205, in lvl_select_init
    self.lvl_select_run()
  File "main.py", line 214, in lvl_select_run
    self.lvl_select_update()
  File "main.py", line 222, in lvl_select_update
    self.all_sprites.update()
  File "/home/macdeth/.local/lib/python3.6/site-packages/pygame/sprite.py", line 462, in update
    s.update(*args)
  File "/home/macdeth/Documents/wvu-runner-game-team/entities.py", line 108, in update
    if self.game.controller is not None:
AttributeError: 'Game' object has no attribute 'controller'
```

**Comment by MacDeth** [comment]
This issue has been resolved by commit 4208e3e437c79ca8744b8ce174b2f6ca55c0194a
